// 01_Src/01_Client/src/app/views/signup/signup.component.ts
/******************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @CreatedDate           : 2023-03-17 16:02:10                               *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @LastEditDate          : 2023-03-17 16:23:32                               *
 *****************************************************************************/

import { Component, OnInit } from '@angular/core';
import { ApiService } from 'src/app/services/api/api.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent implements OnInit {

  constructor(private api: ApiService) {}

  public  name: string = "";
  public  email: string = "";
  public  pwd: string = "";
  public  conPwd: string = "";

  public  error: boolean = false;
  public  step: number = 1;

  ngOnInit(): void {
    this.next()
  }

  private next() {
    const el = document;
    const _this = this;
    el?.addEventListener('keydown', function(e: any) {
      if (e.key === 'Enter' && _this.step < 5) {
        _this.checkStep()
      }
    });
  }

  public checkStep() {
    let error = false;
    switch (this.step) {
      case 2:
        if(this.name.length < 1) error = true;
        break;

      case 3:
        let mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
        if(!this.email.match(mailformat)) error = true;
        break;

      case 4:
        if (this.pwd != this.conPwd) error = true;
        break;
    }
    if (error) {
      this.error = true;
    } else {
      this.error = false;
      this.step++;
    }
    if (this.step === 5) {
      this.signup();
    }
  }

  signup() {
    this.api.request("POST", "users", {
      name: this.name,
      email: this.email,
      password: this.pwd
    }).then(() => {
      this.step = 6;
    }).catch((error: any) => {
      console.error("Signup error >> "+error)
    })
  }
}

<!--
* @Author                : 0K00<qdouvillez@gmail.com>
* @CreatedDate           : 2023-03-17 15:48:00
* @LastEditors           : 0K00<qdouvillez@gmail.com>
* @LastEditDate          : 2023-04-13 11:03:17
-->

<div id="signup">
  <div *ngIf="step === 1" class="container" style="align-items: center; gap: 2rem; justify-items: center;">
    <div class="title">This is it!</div>
    <div class="subtitle">The first step to becoming an efficient project manager in <i class="blue">Statch</i>.</div>
    <app-button id='toStep2' type='prm' size='md' label="Let’s get started!" (click)='checkStep()' icon='enter' iconPosition='right' />
  </div>
  <div *ngIf="step === 2" class="container" style="align-items: flex-start; gap: 1.5rem;">
    <app-input id="name" ngClass="{{error ? 'invalid' : '' }}" [(value)]="name" placeholder="{{error ? 'Name should not be empty...' : 'Enter your name...'}}" label="{{error ? 'Name should not be empty' : 'Your name'}}" type="prm" size="md" other="full" [isLabel]="true" />
    <app-button id='toStep3' type='prm' size='md' other="full" label="Next" (click)='checkStep()' icon='arrow-right' iconPosition='right' />
  </div>
  <div *ngIf="step === 3" class="container" style="align-items: flex-start; gap: 1.5rem;">
    <app-input id="email" ngClass="{{error ? 'invalid' : '' }}" [(value)]="email" placeholder="{{error ? 'Please enter a valid email...' : 'Enter your email...'}}" label="{{error ? 'Please enter a valid email' : 'Your email'}}" type="prm" size="md" other="full" [isLabel]="true" />
    <app-button id='toStep4' type='prm' size='md' other="full" label="Next" (click)='checkStep()' icon='arrow-right' iconPosition='right' />
  </div>
  <div *ngIf="step === 4" class="container" style="align-items: flex-start; gap: 1.5rem;">
    <app-input id="pwd" ngClass="{{error ? 'invalid' : '' }}" [(value)]="pwd" is="password" placeholder="{{error ? 'Passwords are not matching...' : 'Enter your password...'}}" label="{{error ? 'Passwords are not matching' : 'Enter your password'}}" type="prm" size="md" other="full" [isLabel]="true" />
    <app-input id="conPwd" ngClass="{{error ? 'invalid' : '' }}" [(value)]="conPwd" is="password" placeholder="{{error ? 'Passwords are not matching...' : 'Confirm your password...'}}" label="{{error ? 'Passwords are not matching' : 'Rewrite your password'}}"  type="prm" size="md" other="full" [isLabel]="true" />
    <app-button id='toStep5' type='prm' size='md' other="full" label="Finish" (click)='checkStep()' icon='arrow-right' iconPosition='right' />
  </div>
  <div *ngIf="step === 5" class="container" style="align-items: center; gap: 2rem;">
    <div class="title">Creating User...</div>
    <div class="subtitle">Please wait while creating your account.</div>
  </div>
  <div *ngIf="step === 6" class="container" style="align-items: center; gap: 2rem;">
    <div class="title">Completed!</div>
    <div class="subtitle">Just wait for the person in charge to validate your account.</div>
    <a href="/login">
      <div>
        Return to login<app-icons [ngClass]="'icon'" icon="arrow-right" />
      </div>
    </a>
  </div>
</div>

// 01_Src/01_Client/src/views/signup/Signup.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-21 13:29:09                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-27 16:09:36                                
*                                                                             
-->

<script lang='ts'>
    import { defineComponent } from 'vue';
    import './signup.scss';
    import Input from '@/components/input/Input.vue';
    import Button from '@/components/button/Button.vue';
    export default defineComponent({
        name: 'Signup',
        components: {
          Input,
          Button
        },
        props: [],
        computed: {
        },
        mounted() {
          this.next();
        },
        data() {
            return {
              step: 1
            }
        },
        methods: {
          next() {
            const el = document;
            const _this = this;
            el?.addEventListener('keydown', function(e: any) {
              if (e.key === 'Enter' && _this.step < 5) {
                _this.step += 1;
              }
            });
          }
        }
    });
</script>

<template>
    <div id="signup">
      <div v-if="step === 1" class="container" style="align-items: center; gap: 2rem;">
        <div class="title">This is it!</div>
        <div class="subtitle">The first step to becoming an efficient project manager in <i class="blue">Statch</i>.</div>
        <Button id='toStep2' type='prm' size='md' other="full" label="Let’s get started!" @click='step = 2' icon='enter' iconPosition='right' />
      </div>
      <div v-if="step === 2" class="container" style="align-items: flex-start; gap: 1.5rem;">
        <Input id="name" placeholder="Enter your name..." type="prm" size="md" other="full" isLabel="true" labelText="Your name"/>
        <Button id='toStep3' type='prm' size='md' other="full" label="Next" @click='step = 3' icon='arrowright' iconPosition='right' />
      </div>
      <div v-if="step === 3" class="container" style="align-items: flex-start; gap: 1.5rem;">
        <Input id="email" placeholder="Enter your email..." type="prm" size="md" other="full" isLabel="true" labelText="Your email"/>
        <Button id='toStep4' type='prm' size='md' other="full" label="Next" @click='step = 4' icon='arrowright' iconPosition='right' />
      </div>
      <div v-if="step === 4" class="container" style="align-items: flex-start; gap: 1.5rem;">
        <Input id="pwd" is="password" placeholder="Enter your password..." type="prm" size="md" other="full" isLabel="true" labelText="Enter your password"/>
        <Input id="conPwd" is="password" placeholder="Confirm your password..." type="prm" size="md" other="full" isLabel="true" labelText="Rewrite your password"/>
        <Button id='toStep5' type='prm' size='md' other="full" label="Finish" @click='step = 5' icon='arrowright' iconPosition='right' />
      </div>
      <div v-if="step === 5" class="container" style="align-items: center; gap: 2rem;">
        <div class="title">Completed!</div>
        <div class="subtitle">Just wait for the person in charge to validate your account.</div>
        <a href="/login">
          <div>
            Return to login<i class="icon arrowright"></i>
          </div>
        </a>
      </div>
    </div>
</template>
