// 01_Src/01_Client/src/components/status/Status.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-27 14:51:14                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-27 14:54:12                                
*                                                                             
-->

<script lang="ts">
  import { defineComponent } from 'vue';
  import './status.scss';

  export default defineComponent({
    name: "Status",

    props: {
      icon: {
        type: String,
        default: {
          icon: "icon"
        }
      },
      status: {
        type: String,
        required: true
      }
    }
  });
</script>

<template>
  <i :class="[icon, status]"></i>
</template>

// 01_Src/01_Client/src/app/components/status/status.component.ts
/*****************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>             *
 * @CreatedDate           : 2023-03-17 13:16:59                              *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>             *
 * @LastEditDate          : 2023-03-21 19:36:13                              *
 ****************************************************************************/

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-status',
  templateUrl: './status.component.html',
  styleUrls: ['./status.component.scss']
})
export class StatusComponent {
  @Input() status: string = "";
}

<!--
* @Author                : 0K00<qdouvillez@gmail.com>
* @CreatedDate           : 2023-03-17 13:39:00
* @LastEditors           : 0K00<qdouvillez@gmail.com>
* @LastEditDate          : 2023-03-24 11:16:47
*
-->

<div class="center">
  <app-icons [ngClass]="'icon '+status" icon="{{status}}" />
</div>
