// 01_Src/01_Client/src/components/breadcrumbs/Breadcrumbs.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-03-02 15:34:55                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-03-02 16:15:14                                
*                                                                             
-->

<script lang='ts'>
    import { defineComponent } from 'vue';
    import './breadcrumbs.scss';

    export default defineComponent({
        name: 'Breadcrumbs',

        props: [],

        computed: {
            
           crumbs() {
                console.log(this.$route);
                
                return {
                    path: this.$route.fullPath,
                    name: this.$route.params
                };
            }
        },

        data() {
            return {
                type: 'test',
                id: 'test'
            }
        },

        methods: {}
    });
</script>

<template>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="item" v-for="(route, index) in crumbs">
                <router-link :to="crumbs.path">{{ crumbs.name }}</router-link>
            </li>
        </ol>
    </nav>
</template>

// 01_Src/01_Client/src/app/components/breadcrumbs/breadcrumbs.component.ts
/******************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @CreatedDate           : 2023-03-17 12:23:56                               *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @LastEditDate          : 2023-03-17 12:23:59                               *
 *****************************************************************************/

import { Component } from '@angular/core';

interface CrumbsInterface {
  name: string,
  path: string
}

@Component({
  selector: 'app-breadcrumbs',
  templateUrl: './breadcrumbs.component.html',
  styleUrls: ['./breadcrumbs.component.scss']
})
export class BreadcrumbsComponent {

  public crumbs: Array<CrumbsInterface> = [];

}

<!--
* @Author                : Adrien Lanco<adrienlanco0@gmail.com>
* @CreatedDate           : 2023-03-17 12:19:36
* @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>
* @LastEditDate          : 2023-03-17 12:19:37
-->

<nav>
  <ol class="breadcrumb">
      <li class="item" *ngFor="let crumb in crumbs; let index = index">
          <p [routerLink]="crumb.path">{{ crumb.name }}</p>
      </li>
  </ol>
</nav>
