// 01_Src/01_Client/src/app/components/collapse/collapse.component.ts
/******************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @CreatedDate           : 2023-03-17 13:07:58                               *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @LastEditDate          : 2023-03-17 14:49:00                               *
 *****************************************************************************/

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-collapse',
  templateUrl: './collapse.component.html',
  styleUrls: ['./collapse.component.scss']
})
export class CollapseComponent {
  @Input() label: string = "";
  @Input() status: string = "";

  @Input() type: string = "";
  @Input() id: string = "";

  @Input() depth: number = 0;

  @Input() noContent: boolean = false;

  public showCollapse: boolean = false;

  public indent(): Object {
    let transform = this.depth * 16 * this.depth;
    return { transform: 'translate(' + transform + 'px)' };
  }

  public toggleCollapse(): void {
    this.showCollapse = !this.showCollapse;
  }
}

<!--
* @Author                : 0K00<qdouvillez@gmail.com>
* @CreatedDate           : 2023-03-17 12:58:00
* @LastEditors           : 0K00<qdouvillez@gmail.com>
* @LastEditDate          : 2023-03-31 19:06:42
-->

<div class="collapse" [ngClass]="{ 'open': show(), 'close': !show() }">
  <div *ngIf="!other" [ngStyle]="indent()" class="label" [ngClass]="{ 'active': isActive }">
      <div *ngIf="!noContent && !other" class="icons" (click)="toggleCollapse()"
            [ngClass]="{ 'less': show(), 'more': !show() }" >
          <app-icons *ngIf="!show()" [ngClass]="'icon'" icon="chevron-right" />
          <app-icons *ngIf="show()" [ngClass]="'icon'" icon="chevron-down" />
      </div>
      <div *ngIf="!noContent && other" class="icons" (click)="toggleCollapse()"
          [ngClass]="{ 'less': show(), 'more': !show() }" >
        <app-icons *ngIf="!show()" [ngClass]="'icon'" icon="open" />
        <app-icons *ngIf="show()" [ngClass]="'icon'" icon="close" />
      </div>
      <nav class="nav" [routerLink]="[ type+(id? '/'+id : '') ]">
          <div class="link">
              <app-level *ngIf="level" [degree]="level" />
              <div *ngIf="version" class="version">{{ version }}</div>
              <app-status [status]="status"></app-status>
              <div class="text">{{ label | capFL }}</div>
          </div>
      </nav>
  </div>

  <div *ngIf="other" class="label" [ngClass]="{ 'active': isActive }" [ngClass]="[other]" (click)="toggleCollapse()">
    <div *ngIf="!noContent && other" class="icons" [ngStyle]="indent()"
        [ngClass]="{ 'less': show(), 'more': !show() }" >
      <app-icons *ngIf="!show()" [ngClass]="'icon'" icon="open" />
      <app-icons *ngIf="show()" [ngClass]="'icon'" icon="close" />
    </div>
    <nav [routerLink]="[ '/' + type+(id? '/'+id : '') ]">
        <div class="link" [ngStyle]="indent()">
            <app-level *ngIf="level" [degree]="level" />
            <div *ngIf="version" class="version">{{ version }}</div>
            <app-status [status]="status"></app-status>
            <div class="text">{{ label | capFL }}</div>
        </div>
    </nav>
</div>



  <ng-content *ngIf="show()">
  </ng-content>
</div>

// 01_Src/01_Client/src/components/collapse/Collapse.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-27 16:20:24                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-27 17:06:50                                
*                                                                             
-->

<script lang='ts'>
    import { defineComponent } from "vue";
    import './collapse.scss';
    import Status from "../status/Status.vue";

    export default defineComponent({
        name: 'Collapse',

        components: {
          Status  
        },

        props: [ 'label', 'nodes', 'depth', 'status', 'url' ],

        computed: {
            indent() {
                return { transform: `translate(${this.depth * 16 * this.depth}px)` }
            },
            iconCollapse() {
                return {
                    'more': !this.showCollapse,
                    'less': this.showCollapse
                }
            },
            isOpen() {
                return {
                    'close': !this.showCollapse,
                    'open': this.showCollapse
                }
            },
        },

        data() {
            return { showCollapse: false }
        },

        methods: {
            toggleCollapse() {
                this.showCollapse = !this.showCollapse;
            }
        }
    });
</script>

<template>
    <div class="collapse" :class="isOpen">
        <RouterLink :to="url">
            <div class="label">
                <div v-if="nodes" class="icons" :style="indent" :class="iconCollapse" @click="toggleCollapse">
                    <i v-if="!showCollapse" class="icon chevron-right"></i>
                    <i v-if="showCollapse" class="icon chevron-down"></i>
                </div>
                <div class="link" :style="indent">
                    <Status :status="status" />
                    <div class="text">{{ label }}</div>
                </div>
            </div>
        </RouterLink>
        <Collapse
            v-if="showCollapse"
            v-for="node in nodes"
            :to="node.url"
            :status="node.status"
            :nodes="node.nodes"
            :label="node.label"
            :depth="depth + 1"
        >
        </Collapse>
    </div>
</template>
