// 01_Src/01_Client/src/views/projects/Projects.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-22 09:18:40                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-25 17:18:36                                
*                                                                             
-->

<script lang='ts'>
    import { defineComponent } from 'vue';
    import './projects.scss';
    import Button from '@/components/button/Button.vue';

    export default defineComponent({
        name: 'Projects',

        components: {
            Button,
        },

        props: [],

        computed: {},

        data() {
            return {
                content: [
                    {status: 0, version: '0.1', name: 'Lorem', created: 'Jan 10', id: '/create'},
                    {status: 0, version: '0.1', name: 'Lorem', created: 'Jan 10', id: '/create'},
                    {status: 0, version: '0.1', name: 'Lorem', created: 'Jan 10', id: '/create'},
                ]
            }
        },

        methods: {}
    });
</script>

<template>
  <div id="projects" class="main">
    <div class="header">
        <div class="right">
            <h2>Projects</h2>
            <Button id="filter" type="fth" size="md" label="Add filter +" />
        </div>
        <Button id="newProject" type="scnd" size="md" label="New project (Alt + P)" />
    </div>
    <div class="content" >
        <a v-for="item in content" :href="item.id">
            <div class="right">
                <div class="status">{{ item.status }}</div>
                <div class="version">{{ item.version }}</div>
                <div class="name">{{ item.name }}</div>
            </div>
            <div class="date">{{ item.created }}</div>
        </a>
        
    </div>
  </div>
</template>

// 01_Src/01_Client/src/app/views/projects/projects.component.ts
/*****************************************************************************
 * @Author                : AdrienLanco0<adrienlanco0@gmail.com>             *
 * @CreatedDate           : 2023-03-17 17:24:53                              *
 * @LastEditors           : AdrienLanco0<adrienlanco0@gmail.com>             *
 * @LastEditDate          : 2023-03-23 17:23:43                              *
 ****************************************************************************/

import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from 'src/app/services/api/api.service';
import { ProjectInterface, ProjectListService, VersionInterface } from 'src/app/services/project-list/project-list.service';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss']
})
export class ProjectsComponent implements OnInit {

  constructor(private api: ApiService,
              private router: Router) {
    ProjectListService.projectListChange.subscribe((value) => {
      this.projectList = value;
    })
  }


  public projectList: Array<ProjectInterface>= new Array<ProjectInterface>;

  ngOnInit() {
  }

  async openNewProject(): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      this.api.request("POST", "projects", {
        name: "New Project",
        description: "My awesome new project"
      }).then((ret: any) => {
        if (ret.id)
          this.router.navigate(["/project/", ret.id ])
        else
          console.error("New Project 1 error >> "+ret)
      }).catch((error: any) => {
        console.error("New project 2 error >> "+error)
      })
    })
  }
}

<!--
* @Author                : 0K00<qdouvillez@gmail.com>
* @CreatedDate           : 2023-03-17 17:17:00
* @LastEditors           : 0K00<qdouvillez@gmail.com>
* @LastEditDate          : 2023-03-31 14:59:39
-->

<div id="projects" class="main">
  <div class="header">
      <div class="right">
          <h2>Projects</h2>
          <!-- <app-button id="filter" type="fth" size="md" label="Add filter +" /> -->
      </div>
      <app-button id="newProject" type="scnd" size="md" label="New project (Alt + P)" (click)='openNewProject()' />
  </div>
  <div class="content" >
      <a *ngFor="let project of projectList" [href]="'project/'+project.id">
          <div class="right">
              <div class="status"><app-status [status]="project.status" /></div>
              <div class="version">{{ project.actualVersion }}</div>
              <div class="name">{{ project.name | capFL }}</div>
          </div>
          <div class="date">{{ project.created | dateDifference }}</div>
      </a>
  </div>
</div>
