// 01_Src/01_Client/src/app/views/login/login.component.ts
/******************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @CreatedDate           : 2023-03-17 16:23:16                               *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @LastEditDate          : 2023-03-17 18:56:57                               *
 *****************************************************************************/

import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from 'src/app/services/api/api.service';

import { UserService } from 'src/app/services/user/user.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  constructor(private router: Router,
              private api: ApiService) {
  }

  public email: string = "";
  public password: string = "";

  public message: string = "";

  ngOnInit() {
    if (UserService.isConnected())
      this.router.navigate(["/"])
  }

  public login(): void {
    let mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    if (!this.email.match(mailformat)) {

      this.message = "Please entere a valid email address"
      console.log(this.message);

      return;
    }

    this.api.request("POST", "login", {
      email: this.email,
      password: this.password
    }).then((ret: any) => {
      UserService.setUser(ret)
      this.router.navigate(["/projects"])
    }).catch((error: any) => {
      console.error("Login error >> "+error)
    })
  }

}

<!--
* @Author                : Adrien Lanco<adrienlanco0@gmail.com>
* @CreatedDate           : 2023-03-17 15:25:00
* @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>
* @LastEditDate          : 2023-03-17 18:56:50
-->

<div id="login">
  <img src="/assets/logotype.svg" alt="Statch logotype" width="102" height="28">
  <div class="container">
    <app-input  id="mail" [(value)]="email" placeholder="Enter your email..."
                type="prm" size="md" other="full" />
    <app-input  id="pwd" [(value)]="password" is="password" placeholder="Enter your password..."
                type="prm" size="md" other="full" />
    <app-button id='btnLogin' type='prm' size='md' label='Open'
                other="full" (click)='login()' icon='enter' iconPosition='right' />
    <a href="/signup">
      <div>
        Create your account<i class="icon arrowright"></i>
      </div>
    </a>
  </div>
</div>

// 01_Src/01_Client/src/views/login/Login.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : Invalid Date                                       
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-23 14:35:37                                
*                                                                             
-->


<script lang='ts'>
    import { defineComponent } from 'vue';
    import './login.scss';
    import Input from '@/components/input/Input.vue';
    import Button from '@/components/button/Button.vue';

    export default defineComponent({
        name: 'Login',

        components: {
          Input,
          Button
        },

        props: [],

        computed: {},

        data() {
            return {}
        },

        methods: {

         login() {
          console.log('click');
         }
        }
    });
</script>

<template>
    <div id="login">
      <img src="@/assets/logotype.svg" alt="Statch logotype" width="102" height="28">
      <div class="container">
        <Input id="mail" placeholder="Enter your email..." type="prm" size="md" other="full" />
        <Input id="pwd" is="password" placeholder="Enter your password..." type="prm" size="md" other="full" />
        <Button id='btnLogin' type='prm' size='md' label='Open' @click='login' icon='enter' iconPosition='right' />
        <a href="/create">
          <div>
            Create your account<i class="icon arrowright"></i>
          </div>
        </a>
      </div>
    </div>
</template>
