// src/client/src/app/components/search-bar/search-bar.component.ts
/*****************************************************************************
 * @Author                : Jbristhuille<jean-baptiste@halfsquare.fr>        *
 * @CreatedDate           : 2023-03-20 16:31:02                              *
 * @LastEditors           : Jbristhuille<jean-baptiste@halfsquare.fr>        *
 * @LastEditDate          : 2023-09-29 15:30:05                              *
 ****************************************************************************/

/* SUMMARY
  * Imports
  * Interfaces
  * Services
*/

/* Imports */
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { Router } from "@angular/router";
/***/

/* Interfaces */
export interface ISearchResponse {
  id: string,
  name: string,
  type: string,
  icon: string,
}
/***/

/* Services */
import { RequestService } from "src/app/services/request.service";
/***/

@Component({
  selector: "component-search-bar",
  templateUrl: "./search-bar.component.html",
  styleUrls: ["./search-bar.component.scss"]
})
export class SearchBarComponent {
  @Input() onSearch: boolean;
  @Output() onSearchChange = new EventEmitter<boolean>();
  public query: string = "";
  public results: Array<ISearchResponse> = []; // TO DO Cmd Interface
  public resultsSelected: any = [];
  public focusedResult: number = -1;
  public stepSearch: number = 0;
  public showBlock: boolean = false;
  public placeholderSearch: string = "Search projects or commands line...";

  constructor(private api: RequestService,
              private router: Router) {
  }


  /**
  * Updates the query data property and calls the search function with the updated query.
  */
  public handleInput(): void {
    this.search(this.query);
  }
  /***/

  /**
  * Sends request to the demo dataverse API to retrieve search results for the given query.
  * @param query - The search query entered by the user.
  */
  public search(query: string): Promise<any> {
    return new Promise((resolve, reject) => {
      this.api.post("api/search", { query: query })
        .then(data => {
          this.focusedResult = 0;
          this.results = data as ISearchResponse[];
          resolve(data);
        })
        .catch(error => {
          console.error(error);
          this.results = [];
          reject(error);
        });
    });
  }
  /***/

  /**
  * Increments the focusedResult data property by 1, unless it is already at the maximum value (the last result).
  *
  */
  public focusNextResult(): void {
    this.focusedResult = Math.min(this.focusedResult + 1, this.results.length - 1);
    this.followFocus("start");
  }
  /***/

  /**
  * Decrements the focusedResult data property by 1, unless it is already at the minimum value (the first result).
  */
  public focusPrevResult(): void {
    this.focusedResult = Math.max(this.focusedResult - 1, 0);
    this.followFocus("end");
  }
  /***/

  /**
  * sets the focusedResult data property to the given index.
  * @param index - The index of the result to focus
  */
  public focusResult(index: number): void {
    this.focusedResult = index;
  }
  /***/

  /**
  * Follow the selected result and scroll into element.
  */
  public followFocus(event: string): void {
    let focus = document.getElementsByClassName("focused");

    if(event === "end") {
      focus[0].scrollIntoView({ behavior: "smooth", block: "end" });
    }
    if(event === "start") {
      focus[0].scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }
  /***/

  /**
  * Logs the selected result to the console.
  * @param {any} result - The result to be selected
  */
  public selectResult(result: any): void {
    let ptt = [ "project", "task", "ticket"];
    if (ptt.includes(result.type))
      this.redirect(result);
  }
  /***/

  public handle(event: any): void {
    if(!event.altKey && event.key === "Enter")  {
      console.log("Enter");
      this.handleEnter();
    } if (event.altKey && event.key === "Enter") {
      console.log("Alt + Enter");
      this.handleCommands();
    }
  }

  public redirect(result: any): void {
    this.router.navigate([result.type+"s", result.id ]);
    this.onSearchChange.emit(false);
  }

  public handleCommands(): void {
    if (this.focusedResult > -1 && this.results.length > 0) {
      this.commands(this.results[this.focusedResult]);
    }
  }

  public commands(result: any): void {
    this.placeholderSearch = "Search in...";
    this.resetInput();
    this.resultsSelected.push(result);
    this.stepSearch += 1;
  }

  public returnStep(step: number): void {
    console.log(step);
    if(step === 0) {
      this.resultsSelected = [];
      this.stepSearch = 0;
      console.log("toto");

      return;
    }
    this.stepSearch -= this.resultsSelected.length - step;
    this.resultsSelected.splice(step);

  }

  private resetInput(): void {
    this.results = [];
    this.query = "";
  }

  /**
  * Selects the currently focused result if there is one.
  */
  public handleEnter(): void {
    if (this.focusedResult > -1 && this.results.length > 0) {
      this.redirect(this.results[this.focusedResult]);
    }
  }
  /***/
}

<!--
* @Author                : Jbristhuille<jean-baptiste@halfsquare.fr>
* @CreatedDate           : 2023-03-17 15:15:00
* @LastEditors           : Jbristhuille<jean-baptiste@halfsquare.fr>
* @LastEditDate          : 2023-09-29 15:23:50
-->

<div class="searchBar">
  <div class="searchInput">
    <i *ngIf="stepSearch < 1" class="icon search"></i>
    <div *ngIf="stepSearch > 0" (click)="returnStep(0)" class="return">
      <i  class="icon chevron-left"></i>
    </div>
    <div class="resultContainer">

      <div *ngIf="resultsSelected.length > 3" (mouseenter)="showBlock = true" (mouseleave)="showBlock = false">
        <div class="label-search">
          ...
        </div>
        <div *ngIf="showBlock" class="label-block">
          <div class="item">
            <div *ngFor="let item of resultsSelected; let i = index" [ngClass]="{'invSearch': i == resultsSelected.length - 1}">
              <div class="label-search">
                <div class="text">
                  <i  class="icon {{item.icon}}"></i>
                  {{item.name}}
                </div>
                <div (click)="returnStep(i)" class="return">
                  <i  class="icon cross-2"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div *ngFor="let item of resultsSelected; let i = index" [ngClass]="{'invSearch': resultsSelected.length > 3 && i !== resultsSelected.length - 1}">
        <div [ngClass]="{'not-last-item': i !== resultsSelected.length - 1}" class="label-search">
          <div class="text">
            <i  class="icon {{item.icon}}"></i>
            {{item.name}}
          </div>
          <div (click)="returnStep(i)" class="return">
            <i  class="icon cross-2"></i>
          </div>
        </div>
      </div>

    </div>
    <input type="text" id="inputSearch" autocomplete="off"
      placeholder="{{placeholderSearch}}"
      [(ngModel)]="query"
      appFocusOnShow
      (ngModelChange)="handleInput()"
      (keydown.arrowDown)="focusNextResult()"
      (keydown.arrowUp)="focusPrevResult()"
      (keydown)="handle($event)" />
  </div>

  <div *ngIf="history.length > 0" class="subtitle">Last search</div>

  <ul class="history" *ngIf="history.length > 0">
    <li *ngFor="let result of history; let index = index"
      (click)="selectHistory(result)">
      <core-icon  icon="{{result.icon}}" />
      {{ result.name }}
    </li>
  </ul>

  <div *ngIf="results.length > 0" class="subtitle">Results</div>

  <ul class="results" *ngIf="results.length > 0">
    <li *ngFor="let result of results; let index = index"
      [ngClass]="{ focused: index === focusedResult }"
      (click)="selectResult(result)"
      (mouseover)="focusResult(index)">
      <core-icon  icon="{{result.icon}}" />
      {{ result.name }}
    </li>
  </ul>

  <div *ngIf="results.length > 0" class="footer">
    Go to
    <div>
      <core-icon icon="enter"/>
    </div>
  </div>
</div>

// 01_Src/01_Client/src/compositions/searchBar/SearchBar.vue
<!--

  File: SearchBar.vue

  Description: Search Bar Component with live search and keyboard navigation

  Author: @qdouvillez

  Date: 20 Dec 2022 at 17:38

  Last Modified: 24 Dec 2022 at 17:39

  Copyright: Copyright 2023, ©Half Square



  Purpose:

  -



  Dependencies:

  - searchBar.scss: Style file



  Notes:

  - Fake api : https://demo.dataverse.org/api/search?q=${query}



  Summary:

  - mounted
  - handleInput
  - search
  - focusNextResult
  - focusPrevResult
  - focusResult
  - selectResult
  - handleEnter

-->

<script lang='ts'>
    import { defineComponent } from 'vue';
    import './searchBar.scss';

    export default defineComponent({
        name: 'SearchBar',

        components: {
        },

        props: [],

        computed: {},

        data() {
            return {
              query: '',
              results: [],
              focusedResult: -1,
            }
        },

        /*
         * Name: mounted
         *
         * Description: This function is called when the component is mounted. It focuses the input element.
         *
        */
        mounted() {
            document.getElementById("inputSearch")!.focus();
        },
        /***/

        methods: {

            /*
             * Name: handleInput
             *
             * Description: This function is called when the input element's value changes. It updates the query data property and calls the search function with the updated query.
             *
            */
            handleInput() {
              this.search(this.query);
            },
            /***/

            /*
             * Name: search
             *
             * Description: This function sends a fetch request to the demo dataverse API to retrieve search results for the given query.
             *
             * @param {string} query - The search query entered by the user.
             *
            */
            search(query: string) {
                return new Promise((resolve, reject) => {
                  fetch(`https://demo.dataverse.org/api/search?q=${query}`)
                    .then(response => response.json())
                    .then(data => {
                      this.focusedResult = 0;
                      this.results = data.data.items;
                      resolve(data);
                    })
                    .catch(error => {
                      console.error(error);
                      this.results = [];
                      reject(error);
                    });
                });
            },
            /***/

            /*
             * Name: focusNextResult
             *
             * Description: This function increments the focusedResult data property by 1, unless it is already at the maximum value (the last result).
             *
            */
            focusNextResult() {
              this.focusedResult = Math.min(this.focusedResult + 1, this.results.length - 1);
              this.followFocus()
            },
            /***/

            /*
             * Name: focusPrevResult
             *
             * Description: This function decrements the focusedResult data property by 1, unless it is already at the minimum value (the first result).
             *
            */
            focusPrevResult() {
              this.focusedResult = Math.max(this.focusedResult - 1, 0);
              this.followFocus()
            },
            /***/

            /*
             * Name: focusResult
             *
             * Description: This function sets the focusedResult data property to the given index.
             *
             * @param {number} index - The index of the result to focus
             *
            */
            focusResult(index: number) {
              this.focusedResult = index;
            },
            /***/

            /*
             * Name: followFocus
             *
             * Description: This function follow the selected result and scroll into element.
             *
             *
            */
            followFocus() {
              const selectedResult = document.getElementById(`result-${this.focusedResult}`);
              if (selectedResult) {
                selectedResult.scrollIntoView({ behavior: 'smooth' });
              }
            },
            /***/

            /*
             * Name: selectResult
             *
             * Description: This function logs the selected result to the console.
             *
             * @param {any} result - The result to be selected
             *
            */
            selectResult(result: any) {
              console.log('clicked', result)
            },
            /***/

            /*
             * Name: handleEnter
             *
             * Description: This function selects the currently focused result if there is one.
             *
            */
            handleEnter() {
              if (this.focusedResult > -1) {
                this.selectResult(this.results[this.focusedResult]);
              }
            },
        }
    });
</script>

<template>
  <div class="searchBar">
    <div class="searchInput">
          <i class="icon search"></i>
          <input type="text" id="inputSearch" autocomplete="off" placeholder="Search for commands or in projects..." v-model="query" @input="handleInput" @keydown.down="focusNextResult" @keydown.up="focusPrevResult" @keydown.enter="handleEnter" />
    </div>
    <Transition name="nested">
        <div v-if="results.length > 0" class="subtitle">Results</div>
    </Transition>
    <Transition name="nested">
        <ul class="results" v-if="results.length > 0">
          <li v-for="(result, index) in results" :key="index" :ref="'result-' + index" :id="'result-' + index" :class="{ focused: index === focusedResult }" @click="selectResult(result)" @mouseover="focusResult(index)">{{ result.name }}</li>
        </ul>
    </Transition>
    <Transition name="nested">
        <div v-if="results.length > 0" class="footer">
          Go to
          <div class="shortcut"><i class="icon enter"></i></div>
        </div>
    </Transition>
  </div>
</template>
