// 01_Src/01_Client/src/app/components/avatar/avatar.component.ts
/*****************************************************************************
 * @Author                : 0K00<qdouvillez@gmail.com>                       *
 * @CreatedDate           : 2023-03-17 12:11:36                              *
 * @LastEditors           : 0K00<qdouvillez@gmail.com>                       *
 * @LastEditDate          : 2023-03-25 17:27:13                              *
 ****************************************************************************/

import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-avatar',
  templateUrl: './avatar.component.html',
  styleUrls: ['./avatar.component.scss']
})
export class AvatarComponent implements OnInit {
  @Input() userId: string = "";

  @Input() imgPath: string = "";
  @Input() alt: string = "";
  @Input() userName: string = "";

  public classes: string = "";

  ngOnInit() {
    this.userName = this.userName.charAt(0);
  }
}

<!--
* @Author                : Jbristhuille<jean-baptiste@halfsquare.fr>
* @CreatedDate           : 2023-03-17 12:09:00
* @LastEditors           : Jbristhuille<jean-baptiste@halfsquare.fr>
* @LastEditDate          : 2023-05-11 14:54:01
-->

<ng-container *ngIf="imgPath">
  <div routerLink="{{ 'user/'+userId }}" class="avatar {{ classes }}">
    <img *ngIf="imgPath != null" src="{{ env.SERVER_URL }}/{{ imgPath }}" alt="{{ alt }}" />
  </div>
</ng-container>

<ng-container *ngIf="!imgPath">
  <div routerLink="{{ 'user/'+userId }}" class="{{ classes }} avatar no-img">
    {{ userName ? userName[0] : "" }}
  </div>
</ng-container>

// 01_Src/01_Client/src/components/avatar/Avatar.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-23 10:21:44                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-23 10:30:34                                
*                                                                             
-->

<script lang='ts'>
    import { defineComponent } from 'vue';
    import './avatar.scss';

    export default defineComponent({
        name: 'Avatar',

        components: {},

        props: {
          url: {
            type: String,
          },
          alt: {
            type: String,
          },
          id: {
            type: String,
            required: true
          }
        },

        computed: {
          classes() {
            return {
              avatar: true,
            };
          }
        },
        methods: {}
    });
</script>

<template>
  <div :id="id" :class="classes">
    <img v-if="url != null" :src="url" :alt="alt" />
  </div>
</template>
