// 01_Src/01_Client/src/app/compositions/comment/comment.component.ts
/******************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @CreatedDate           : 2023-03-17 13:46:29                               *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @LastEditDate          : 2023-03-17 13:47:01                               *
 *****************************************************************************/

import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-comment',
  templateUrl: './comment.component.html',
  styleUrls: ['./comment.component.scss']
})
export class CommentComponent {
  @Input() userId: string = "md";
  @Input() name: string = "";
  @Input() lastName: string = "";
  @Input() email: string = "";
  @Input() imgPath: string = "";
  @Input() created: string = "";
  @Input() content: string = "";
}

<!--
* @Author                : 0K00<qdouvillez@gmail.com>
* @CreatedDate           : 2023-03-17 11:57:00
* @LastEditors           : 0K00<qdouvillez@gmail.com>
* @LastEditDate          : 2023-05-11 16:38:49
-->

<div class="comment">
  <div class="header">
    <div class="user">
      <div class="img">
        <app-avatar [userId]="userId" [imgPath]="imgPath" [alt]="name + 'photo'" [userName]="name"></app-avatar>
      </div>
      <div class="info">{{ name | capFL }} {{ lastName | capFL }}, {{ created | dateDifference }}</div>
    </div>
    <app-button *ngIf="userId === actualUser.id" (click)="onDelete()" label="Delete" size="sm" type="trd"  />
  </div>
  <div class="content" [id]="id"></div>
</div>

// 01_Src/01_Client/src/compositions/comment/Comment.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-23 12:56:17                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-23 13:30:50                                
*                                                                             
-->

<script lang="ts">
    import { defineComponent } from "vue";
    import './comment.scss';
    import Avatar from "@/components/avatar/Avatar.vue";

    export default defineComponent({
        name: 'Comment',

        components: {
          Avatar,
        },

        props: {
          id: {
            type: String,
            required: true
          },
          name: {
            type: String,
            required: true
          },
          lastName: {
            type: String,
            required: true
          },
          email: {
            type: String,
          },
          img: {
            type: String,
          },
          created: {
            type: String,
            required: true
          },
          content: {
            type: String,
            required: true
          }
        },

        computed: {},
    });
</script>

<template>
  <div class="comment">
    <div class="img"><Avatar :id="id" :url="img" :alt="name + 'photo'" /></div>
    <div class="info">{{ name }} {{ lastName }}, {{ created }} ago</div>
    <div class="content">{{ content }}</div>
  </div>
</template>
