// 01_Src/01_Client/src/components/breadcrumbs/Breadcrumbs.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-03-02 15:34:55                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-03-02 16:15:14                                
*                                                                             
-->

<script lang='ts'>
    import { defineComponent } from 'vue';
    import './breadcrumbs.scss';

    export default defineComponent({
        name: 'Breadcrumbs',

        props: [],

        computed: {
            
           crumbs() {
                console.log(this.$route);
                
                return {
                    path: this.$route.fullPath,
                    name: this.$route.params
                };
            }
        },

        data() {
            return {
                type: 'test',
                id: 'test'
            }
        },

        methods: {}
    });
</script>

<template>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="item" v-for="(route, index) in crumbs">
                <router-link :to="crumbs.path">{{ crumbs.name }}</router-link>
            </li>
        </ol>
    </nav>
</template>

// src/client/src/app/components/breadcrumbs/breadcrumbs.component.ts
/*****************************************************************************
 * @Author                : 0K00<qdouvillez@gmail.com>                       *
 * @CreatedDate           : 2023-09-12 14:26:16                              *
 * @LastEditors           : 0K00<qdouvillez@gmail.com>                       *
 * @LastEditDate          : 2023-11-17 01:00:02                              *
 ****************************************************************************/

import { Component, Input } from "@angular/core";

/**
 * Interface of breadcrumbs with path and name (label text).
 */
interface CrumbsInterface {
  name: string,
  path: string,
  collection: string
}

/**
 * Breadcrumbs component
 */
@Component({
  selector: "component-breadcrumbs",
  templateUrl: "./breadcrumbs.component.html",
  styleUrls: ["./breadcrumbs.component.scss"]
})
export class BreadcrumbsComponent {

  /**
   * List of items for the breadcrumbs hierarchy.
   */
  @Input()
    crumbs: Array<CrumbsInterface> = [];

  public reject: string[] = ["labels", "smtp", "users"];

}

<!--
* @Author                : 0K00<qdouvillez@gmail.com>
* @CreatedDate           : 2023-09-12 14:01:00
* @LastEditors           : 0K00<qdouvillez@gmail.com>
* @LastEditDate          : 2023-11-17 00:59:51
-->

<nav>
  <ol class="breadcrumb">
      <li class="item" *ngFor="let crumb of crumbs; let index = index">
          <a [routerLink]="[crumb.path]">{{ crumb.name | recovery:"name":crumb.collection:reject | async }}</a>
      </li>
  </ol>
</nav>
