// 01_Src/01_Client/src/components/progressBar/ProgressBar.vue
<!--
Author – @0K00
Create Time – 2022-11-04 10:19
Description – Progress Bar component
-->

<script lang="ts">
    import { defineComponent } from "vue";
    import './progressBar.scss';

    export default defineComponent({
        name: 'ProgressBar',

        props: {
            value: {
                type: Number,
                required: true
            },
            id: {
                type: String,
                required: true
            }
        },

        computed: {
            classes() {
                return {
                  prbar: true,
                };
            },
            size() {
                return 'width: ' + this.value + '%';
            }
        },
    });
</script>

<template>
    <div :id='id' :class='classes'>
        <div class='prbar-title'>Advancement</div>
        <div class='prbar-container'>
            <div class='prbar-parent'>
                <div class='prbar-child' :style='size'></div>
            </div>
            <div class='prbar-value'>{{ value }}% done</div>
        </div>
    </div>
</template>

// 01_Src/01_Client/src/app/components/progress-bar/progress-bar.component.ts
/******************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @CreatedDate           : 2023-03-17 13:38:15                               *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @LastEditDate          : 2023-03-17 13:38:24                               *
 *****************************************************************************/

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-progress-bar',
  templateUrl: './progress-bar.component.html',
  styleUrls: ['./progress-bar.component.scss']
})
export class ProgressBarComponent {

  @Input() value: number = 0;
  @Input() id: string = "";
}

<!--
* @Author                : Adrien Lanco<adrienlanco0@gmail.com>
* @CreatedDate           : 2023-03-17 13:33:00
* @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>
* @LastEditDate          : 2023-03-17 13:38:43
-->

<div [ngClass]='{ prbar: true }'>
  <div class='prbar-title'>Advancement</div>
  <div class='prbar-container'>
      <div class='prbar-parent'>
          <div class='prbar-child' [style]="'width: ' + this.value + '%'"></div>
      </div>
      <div class='prbar-value'>{{ value }}% done</div>
  </div>
</div>
