// 01_Src/01_Client/src/components/input/Input.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : Invalid Date                                       
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-23 15:11:59                                
*                                                                             
-->


<script lang='ts'>
    import { defineComponent } from 'vue';
    import './input.scss';

    export default defineComponent({
        name: 'Input',

        props: {
            id: {
                type: String,
                required: true,
            },
            is: {
              type: String,
              default: 'text'
            },
            placeholder: {
                type: String,
                required: false,
            },
            input: {
                type: String,
                default: 'input',
            },
            type: {
                type: String,
                default: 'prm',
                validator(value: string) {
                    return ['prm', 'scnd', 'trd', 'fth'].includes(value);
                },
            },
            size: {
                type: String,
                default: 'md',
                validator(value: string) {
                    return ['sm', 'md', 'l', 'xl'].includes(value);
                },
            },
            other: {
                type: String,
                default: null,
            },
            disabled: {
                type: Boolean,
                default: false
            },
            autocomplete: {
                type: String,
                required: false,
            },
            isLabel: {
              type: String,
              default: 'false'
            },
            labelText: {
              type: String
            }
        },

        computed: {},

        data() {
            return {
                value: ""
            }
        },

        methods: {}
    });
</script>

<template>
    <div :ref="id" :class="[input, type, size, other]">
      <input :type="is" v-model="value" :disabled="disabled" :placeholder="placeholder" :autocomplete="autocomplete" :id="id" />
      <label v-if="isLabel === 'true'" :for="id">{{ labelText }}</label>
    </div>
</template>

// 01_Src/01_Client/src/app/components/input/input.component.ts
/******************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @CreatedDate           : 2023-03-17 13:23:02                               *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @LastEditDate          : 2023-03-17 13:31:17                               *
 *****************************************************************************/

import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.scss']
})
export class InputComponent {
  @Input() id: string = "";

  @Input() isLabel: boolean = false;
  @Input() label: string = "md";
  @Input() placeholder: string = "";

  @Input() type: string = "prm";
  @Input() size: string = "md";
  @Input() other: string = "";

  @Input() is: string = "text";

  @Input() autocomplete: string = "";
  @Input() disabled: boolean = false;

  @Input() value: any;
  @Output() valueChange: EventEmitter<any> = new EventEmitter();
}

<!--
* @Author                : Adrien Lanco<adrienlanco0@gmail.com>
* @CreatedDate           : 2023-03-17 13:20:00
* @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>
* @LastEditDate          : 2023-03-17 13:31:56
-->

<div [class]="['input', type, size, other]">
  <input  [type]="is"
          [(ngModel)]="value"
          (ngModelChange)="valueChange.emit(value)"
          [disabled]="disabled"
          [placeholder]="placeholder"
          [autocomplete]="autocomplete"
          [id]="id" />
  <label *ngIf="isLabel === true" [for]="id">{{ label }}</label>
</div>
