// 01_Src/01_Client/src/compositions/nav/Nav.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-24 16:00:26                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-03-02 14:36:20                                
*                                                                             
-->

<script lang="ts">
    import { defineComponent } from 'vue';
    import './nav.scss';
    import Button from '@/components/button/Button.vue';
    import Collapse from '@/components/collapse/Collapse.vue';

    export default defineComponent({
      name: 'Nav',

      components: {
        Button,
        Collapse
      },

      data() {
            return {
              name: "Half Square",
              tree: {
                label: 'root',
                status: 'progress',
                type: 'project',
                id: '6',
                nodes: [
                    {
                        label: 'item1',
                        status: 'new',
                        type: 'task',
                        id: '7',
                        nodes: [
                            {
                                label: 'item1.1',
                                status: 'done',
                                type: 'ticket',
                                id: '8',
                            },
                            {
                                label: 'item1.2',
                                status: 'wait',
                                type: 'ticket',
                                id: '9',
                            }
                        ]
                    },
                    {
                        label: 'item2',
                        status: 'reject',
                        type: 'task',
                        id: '10',
                    }
                ]
            },
            }
        },
    });

    // team name
    // navigation (projects, activity, add, follow, setting)
    // menu project
</script>

<template>
  <div id="nav">
    <header>
      {{ name }}
    </header>
    <nav>
      <RouterLink to="/projects">
        <Button id="goProjects" type="trd" size="l" icon="dashboard" icon-position="only" />
      </RouterLink>
      <Button id="goActivity" type="trd" size="l" icon="bell" icon-position="only" />
      <Button id="add" type="trd" size="l" icon="plus" icon-position="only" />
      <Button id="goFollow" type="trd" size="l" icon="flag" icon-position="only" />
      <Button id="goSetting" type="trd" size="l" icon="gear" icon-position="only" />
    </nav>
    <div class="menu">
      <Collapse :label="tree.label" :id="tree.id" :type="tree.type" :nodes="tree.nodes" :status="tree.status" :depth="0"></Collapse>
    </div>
  </div>
</template>

// 01_Src/01_Client/src/app/compositions/nav/nav.component.ts
/*****************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>             *
 * @CreatedDate           : 2023-03-17 14:41:39                              *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>             *
 * @LastEditDate          : 2023-03-20 18:11:33                              *
 ****************************************************************************/

import { Component } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { ApiService } from 'src/app/services/api/api.service';
import { CommandService } from 'src/app/services/command/command.service';

import {
  ProjectListService,
  ProjectInterface
} from 'src/app/services/project-list/project-list.service';

@Component({
  selector: 'app-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.scss']
})
export class NavComponent {

  constructor(private api: ApiService,
              private router: Router,
              public command: CommandService) {
    router.events.subscribe((val) => {
      if (val instanceof NavigationEnd) {
        this.handleNavigation(val)
      }
    });
    ProjectListService.projectListChange
    .subscribe((value: Array<ProjectInterface>) => {
      this.projectList = value;
      this.getProjects()
    })
    ProjectListService.projectChange
    .subscribe((project: ProjectInterface) => {
      this.projectId = project.id;
      this.getProjects()
    })
  }

  public projects = new Array<ProjectInterface>;
  public projectList = new Array<ProjectInterface>;

  public url: Array<string> = [];
  public projectId: string = "";

  private handleNavigation(navEnd: NavigationEnd): void {
    this.url = navEnd.urlAfterRedirects.split("/");
  }

  private getProjects(): void {
    if (this.url[1] == 'project' ||
        this.url[1] == 'task' ||
        this.url[1] == 'ticket') {
      if (this.projectId) {
        for (let i = 0; i < this.projectList.length; i++) {
          if (this.projectId == this.projectList[i].id) {
            this.projects = [ this.projectList[i] ];
          }
        }
      } else {
        this.projects = this.projectList;
      }
    } else {
      this.projects = this.projectList;
    }
  };

}

<!--
* @Author                : Adrien Lanco<adrienlanco0@gmail.com>
* @CreatedDate           : 2023-03-17 14:41:00
* @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>
* @LastEditDate          : 2023-03-18 17:00:42
-->

<div id="nav">
  <a href="/projects"><header>Half Square</header></a>
  <nav>
    <app-button id="goProjects" type="trd" size="l"
                icon="dashboard" icon-position="only"
                routerLink="/projects"/>
    <app-button id="goActivity" type="trd" size="l"
                icon="bell" icon-position="only"
                routerLink="/activity" />
    <app-button id="add" type="trd" size="l"
                icon="plus" icon-position="only"
                routerLink="/add"  />
    <app-button id="goFollow" type="trd" size="l"
                icon="flag" icon-position="only"
                routerLink="/follow"  />
    <app-button id="goSetting" type="trd" size="l"
                icon="gear" icon-position="only"
                [routerLink]="['/settings']"  />
  </nav>
  <div class="menu">

    <app-collapse *ngFor="let project of projects"
                  [label]="project.name"
                  [id]="project.id"
                  [type]="'project'"
                  [status]="project.status"
                  (onOpen)="pListS.getProject(project.id)"
                  [depth]="1">

      <app-collapse *ngFor="let task of project.tasks"
                    [label]="task.name"
                    [id]="task.id"
                    [type]="'task'"
                    [status]="task.status"
                    (onOpen)="pListS.getTask(task.id)"
                    [depth]="2">

        <app-collapse *ngFor="let ticket of task.tickets"
                      [label]="ticket.name"
                      [id]="ticket.id"
                      [type]="'ticket'"
                      [status]="ticket.status"
                      [noContent]="true"
                      [depth]="3">
          <app-button class="deleteTicket" type="scnd" size="md"
          [ngStyle]="{transform: 'translate(' + 9*16 + 'px)'}"
          label="Delete ticket (Alt + T)"
          (click)='command.deleteTicket(project.id, ticket)' />
        </app-collapse>

        <app-button class="newTicket" type="scnd" size="md"
        [ngStyle]="{transform: 'translate(' + 4*16 + 'px)'}"
        label="New ticket (Alt + T)"
        (click)='command.openNewTicket(task.id)' />
        <app-button class="deleteTask" type="scnd" size="md"
        [ngStyle]="{transform: 'translate(' + 4*16 + 'px)'}"
        label="Delete task (Alt + N)"
        (click)='command.deleteTask(task)' />
      </app-collapse>


      <app-button class="newTask" type="scnd" size="md"
      [ngStyle]="{transform: 'translateX(' + 16 + 'px)'}"
      label="New task (Alt + N)"
      (click)='command.openNewTask(project.id)' />
      <app-button class="deleteProject" type="scnd" size="md"
      [ngStyle]="{transform: 'translateX(' + 16 + 'px)'}"
      label="Delete project (Alt + N)"
      (click)='command.deleteProject(project.id)' />
    </app-collapse>


    <app-button class="newProject" type="scnd" size="md"
    label="New project (Alt + N)"
    (click)='command.openNewProject()' />
  </div>
</div>
