// 01_Src/01_Client/src/views/project/Project.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-22 11:32:10                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-27 16:16:40                                
*                                                                             
-->

<script lang='ts'>
    import { defineComponent } from 'vue';
    import './project.scss';
    import ProgressBar from "@/components/progressBar/ProgressBar.vue";
    import Avatar from "@/components/avatar/Avatar.vue";
    import Comment from "@/compositions/comment/Comment.vue";
    import Input from "@/components/input/Input.vue";
    import Button from "@/components/button/Button.vue";
    import Label from "@/components/label/Label.vue";
    import Status from '@/components/status/Status.vue';

    export default defineComponent({
        name: 'Project',

        components: {
          ProgressBar,
          Avatar,
          Comment,
          Input,
          Button,
          Label,
          Status
        },

        computed: {},
        
        data() {
            return {
              elements: [
                {status: "done", id: "dc5c7a1", desc: "lorem ipsum...", level: "high", img: "", url: "/create", name: "Randy"},
                {status: "new", id: "dc5c7a1", desc: "lorem ipsum...", level: "low", img: "", url: "/create", name: "Toto"},
                {status: "new", id: "dc5c7a1", desc: "lorem ipsum...", level: "moderate", img: "", url: "/create", name: "Tata"},
                {status: "progress", id: "dc5c7a1", desc: "lorem ipsum...", level: "high", img: "", url: "/create", name: "Oui"},
                {status: "progress", id: "dc5c7a1", desc: "lorem ipsum...", level: "high", img: "", url: "/create", name: "Non"},
                {status: "wait", id: "dc5c7a1", desc: "lorem ipsum...", level: "normal", img: "", url: "/create", name: "Oh"},
                {status: "reject", id: "dc5c7a1", desc: "lorem ipsum...", level: "normal", img: "", url: "/create", name: "Ah"},
              ],
              activity: [
                {img: "0", alt: "oui", name: "Randy", action: "created", id: "dc5c7a1", url: "/create", time: "10 min"},
                {img: "0", alt: "oui", name: "Toto", action: "created", id: "dc5c7a1", url: "/create", time: "10 min"},
                {img: "0", alt: "oui", name: "Tata", action: "created", id: "dc5c7a1", url: "/create", time: "10 min"},
                {img: "0", alt: "oui", name: "Oui", action: "created", id: "dc5c7a1", url: "/create", time: "10 min"},
              ],
              comments: [
                {    
                  "id": "6389f8dcf9f5d32a98630c85",
                  "author": {
                    "_id": "638773e22ef2f4b210dc0fa7",
                    "name": "Jean-Baptiste",
                    "lastName": "BRISTHUILLE",
                    "email": "jbristhuille@gmail.com",
                    "image": ""
                  },
                  "created": "1669986524",
                  "content": "Hello world"
                },
                {
                  "id": "6389f8f48350bb19ecb8225f",
                  "author": {
                    "_id": "638773e22ef2f4b210dc0fa7",
                    "name": "Jean-Baptiste",
                    "lastName": "BRISTHUILLE",
                    "email": "jbristhuille@gmail.com",
                    "image": ""
                  },
                  "created": "1669986549",
                  "content": "Hello world"
                },
              ]
            }
        },

        methods: {
          newComment() {
            let value: any = this.$refs.newCommentContent
            value = value.$data.value
            console.log(value);
          }
        }
    });
</script>

<template>
  <div id="project">
    <div class="project">
      <div class="main">
        <header>
          <h1>Cooking app</h1>
          <h2>Description</h2>
          <p>Lorem</p>
        </header>
        <div class="advancement">
          <ProgressBar id="test" value="15" />
          <div class="elements">
            <a class="element" v-for="element in elements" :href="element.url">
              <div class="block">
                <div class="status"><Status :status="element.status" /></div>
                <div class="id">{{ element.id }}</div>
                <div class="desc">{{ element.desc }}</div>
              </div>
              <div class="block">
                <Label :level="element.level" />
                <Avatar :id="element.name" />
              </div>
            </a>
          </div>
        </div>
        <div class="comments">
          <h2>Comments</h2>
          <Comment 
            v-for="comment in comments"
            :id="comment.id"
            :name="comment.author.name"
            :lastName="comment.author.lastName"
            :content="comment.content"
            :created="comment.created"
          />
          <div class="commentInput">
            <Input id="newCommentContent" ref="newCommentContent" placeholder="Add comment..." />
            <Button id='newComment' type='scnd' size='md' label='Post' @click='newComment' />
          </div>
        </div>
      </div>
      <aside>
        <div class="details">
          <h3>Details</h3>
          <div class="container">
            <h4>Assignee</h4>
            <div class="text">
              <Avatar id="randy" />
              Randy Gouse
            </div>
          </div>
          <div class="container">
            <h4>Owner</h4>
            <div class="text">
              <Avatar id="madelyn" />
              Madelyn Press
            </div>
          </div>
          <div class="container">
            <h4>Version</h4>
            <div class="text">0.10</div>
          </div>
          <div class="container">
            <h4>Status</h4>
            <div class="text"><Status status="progress" /> In progress</div>
          </div>
          <div class="container">
            <h4>No. of tasks</h4>
            <div><a href="/create">4 tasks <i class="icon arrowright"></i></a></div>
          </div>
          <div class="container">
            <h4>No. of tickets</h4>
            <div><a href="/create">14 tickets <i class="icon arrowright"></i></a></div>
          </div>
          <div class="container">
            <h4>No. of docs</h4>
            <div><a href="/create">5 docs <i class="icon arrowright"></i></a></div>
          </div>
          <div class="container">
            <h4>Created</h4>
            <div class="text">Jun 10</div>
          </div>
        </div>
        <div class="activity">
          <h3>Last activity</h3>
          <div class="content" v-for="item in activity">
            <div class="img"><Avatar :id="item.name" /></div>
            <div class="name">{{ item.name }}</div>
            <div class="desc">{{ item.action }} <a :href="item.url">{{ item.id }}</a>, {{ item.time }} ago</div>
          </div>
        </div>
      </aside>
    </div>
  </div>
</template>

// 01_Src/01_Client/src/app/views/project/project.component.ts
/******************************************************************************
 * @Author                : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @CreatedDate           : 2023-03-17 16:49:59                               *
 * @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>              *
 * @LastEditDate          : 2023-03-17 20:03:34                               *
 *****************************************************************************/

import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ProjectInterface, ProjectListService } from 'src/app/services/project-list/project-list.service';

@Component({
  selector: 'app-project',
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.scss']
})
export class ProjectComponent implements OnInit {

  constructor(private route: ActivatedRoute,
              private router: Router) {

  }

  public id: string = "";
  public project: ProjectInterface = {} as ProjectInterface;

  public newCommentContent: string = "";

  public activity : any = [
    {img: "0", alt: "oui", name: "Randy", action: "created", id: "dc5c7a1", url: "/create", time: "10 min"},
    {img: "0", alt: "oui", name: "Toto", action: "created", id: "dc5c7a1", url: "/create", time: "10 min"},
    {img: "0", alt: "oui", name: "Tata", action: "created", id: "dc5c7a1", url: "/create", time: "10 min"},
    {img: "0", alt: "oui", name: "Oui", action: "created", id: "dc5c7a1", url: "/create", time: "10 min"},
  ];

  public comments: any = [
    {
      "id": "6389f8dcf9f5d32a98630c85",
      "author": {
        "_id": "638773e22ef2f4b210dc0fa7",
        "name": "Jean-Baptiste",
        "lastName": "BRISTHUILLE",
        "email": "jbristhuille@gmail.com",
        "image": ""
      },
      "created": "1669986524",
      "content": "Hello world"
    },
    {
      "id": "6389f8f48350bb19ecb8225f",
      "author": {
        "_id": "638773e22ef2f4b210dc0fa7",
        "name": "Jean-Baptiste",
        "lastName": "BRISTHUILLE",
        "email": "jbristhuille@gmail.com",
        "image": ""
      },
      "created": "1669986549",
      "content": "Hello world"
    },
  ];

  async ngOnInit() {
    this.id = this.route.snapshot.paramMap.get('id') || "";
    let project = await ProjectListService.getProject(this.id);
    if (!project)
      this.router.navigate(["/not-found?type=project"])
    else
      this.project = project;

      console.log("fd", project);

  }

  public newComment() {
    console.log(this.newCommentContent);
  }
}

<!--
* @Author                : 0K00<qdouvillez@gmail.com>
* @CreatedDate           : 2023-03-17 16:48:00
* @LastEditors           : 0K00<qdouvillez@gmail.com>
* @LastEditDate          : 2023-04-17 15:04:21
-->

<div id="project">
  <div class="header">
    <app-button type="fth" size="sm" icon="plus" iconPosition="only" (click)="command.openNewTask(project.id)"></app-button>
    <app-assignee-section [buttonOnly]="true" [assignees]="project ? project.assignments : []"
    [data]="project" [dataType]="'project'"></app-assignee-section>
  </div>
  <div class="project">
    <div class="main">
      <header>
        <div class="edit">
          <app-button id="editProj" type="trd" size="md" label="Edit" *ngIf="!onEdit" (click)="redirectToEdit()" />
          <app-button id="deleteProj" type="del" size="md" label="Delete" *ngIf="onEdit" (click)='command.deleteProject(project.id)' />
          <app-button id="saveProj" type="prm" size="md" label="Publish" *ngIf="onEdit" (click)='saveProject()' />
        </div>
        <h1 edtTxt [isEdit]="onEdit" [(value)]="project.name"></h1>
        <h2>Description</h2>
        <p edtTxt [isEdit]="onEdit" [(value)]="project.description"> </p>
      </header>
      <ng-container *ngIf="!windowWidth">
        <div class="details">
          <h3>Details</h3>
          <div class="elements">
            <div class="container">
              <h4>Id</h4>
              <div class="text space">
                {{project.id}}
              </div>
            </div>
            <div class="container">
              <h4>Owner</h4>
              <div class="text space">
                <app-avatar id="madelyn" [userName]="project && project.owner ? project.owner.name : ''" />
                {{ project.owner ? project.owner.name : "" }}
              </div>
            </div>
            <div class="container">
              <h4>Assignee</h4>
              <div class="text">
                <app-assignee-section [assignees]="project ? project.assignments : []"
                                      [data]="project" [dataType]="'project'" />
              </div>
            </div>
            <div class="container">
              <h4>Version</h4>
              <div class="text space">
                <app-versions-section [isEdit]="true" [isProject]="true"
                    [version]="getProjectVersion()" (versionNameChange)="changeProjectVersion($event)" />
              </div>
            </div>
            <div class="container">
              <h4>Status</h4>
              <div class="text space">
                <app-status-labeled [isEdit]="true" [(status)]="project.status" (statusChange)="command.editProject(this.project)"/>
              </div>
            </div>
            <div class="container">
              <h4>Labels</h4>
              <div class="text">
                <app-labels-section placeholder="Select label" [(labels)]="project.labels" (labelsChange)="command.editProject(this.project)" />
              </div>
            </div>
            <div class="container">
              <h4>No. of tasks</h4>
              <div class="text space"><a href="/create">
                {{ project && project.tasks ? project.tasks.length : '0' }}
                {{ project && project.tasks && project.tasks.length > 1 ? "tasks" : "task"}}
                <app-icons [ngClass]="'icon'" icon="arrow-right" />
              </a></div>
            </div>
            <div class="container">
              <h4>Created</h4>
              <div class="text space">{{ project.created | dateDifference }}</div>
            </div>
          </div>
        </div>
      </ng-container>
      <div class="advancement">
        <app-progress-bar id="test" [value]="advancement" />
        <div class="tasks">
          <div class="filter">
            <div class="tabs">
              <div class="tab showAll" [ngClass]="!showAll ? 'selected' : ''" (click)="showAll = false; showSelector = false; triggerShow()">
                <app-icons [ngClass]="'icon'" icon="fries"></app-icons>
              </div>
              <div class="tab selector showFilter" [ngClass]="showAll ? 'selected' : ''" (click)="showAll = true; triggerShow(selectVersion.id)">
                <div class="control">
                  <app-icons [ngClass]="'icon'" icon="straw"></app-icons>
                  <div class="select" (click)="showSelector = !showSelector;" @tab *ngIf="showAll">
                    {{selectVersion.name ? selectVersion.name : "Version"}}
                    <app-icons [ngClass]="'icon'" icon="{{showSelector ? 'chevron-up' : 'chevron-down'}}"></app-icons>
                  </div>
                </div>
                <div @nested *ngIf="showSelector" class="options">
                  <div class="container">
                    <div class="option" *ngFor="let option of options" (click)="selectVersion = option; showSelector = false; triggerShow(option.id)">
                      {{option.name}}
                    </div>
                    <div class="no option" *ngIf="options.length < 1">
                      No version
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <a class="task" *ngFor="let task of advancementTasks" [href]="'/task/'+task.id">
            <div class="container">
              <div class="block">
                <div class="right">
                  <div class="status"><app-status [status]="task.status" /></div>
                  <div *ngIf="task.targetVersion && task.targetVersion.name" class="version">{{ task.targetVersion.name }}</div>
                  <div class="name">{{ task.name }}</div>
                </div>
              </div>
              <div class="block">
                <ng-container *ngIf="task.labels.length < 4">
                  <div class="labels" *ngFor="let label of task.labels">
                    <app-labels name="{{label.name}}" color="{{label.color}}"></app-labels>
                  </div>
                </ng-container>
                <ng-container *ngIf="task.labels.length > 3">
                  <div class="labels" *ngFor="let label of task.labels | slice:0:1">
                    <app-labels name="{{label.name}}" color="{{label.color}}"></app-labels> + {{ task.labels.length - 1 }} {{(task.labels.length - 1) > 1 ? 'others' : 'other'}}
                  </div>
                </ng-container>
                <app-level [degree]="task.level" />
                <app-avatar [userId]="task.owner.id" [userName]="task.owner.name" />
              </div>
            </div>
          </a>

          <a class="task add" (click)="command.openNewTask(project.id)">
            <app-icons [ngClass]="'icon'" icon="plus" />
            Create new Task
          </a>
        </div>
      </div>
      <ng-container *ngIf="!windowWidth">
        <div class="activity">
          <h3>Last activity</h3>
          <div class="content" *ngFor="let item of activity">
            <div class="img"><app-avatar [id]="item.name" [userName]="item.name" /></div>
            <div class="name">{{ item.name }}</div>
            <div class="desc">{{ item.action }} <a [href]="item.url">{{ item.id }}</a>, {{ item.time | dateDifference }}</div>
          </div>
        </div>
      </ng-container>
      <app-comments-section targetType="projects" [targetId]="project.id" [comments]="project.comments" />
    </div>
    <aside *ngIf="windowWidth">
      <div class="details">
        <h3>Details</h3>
        <div class="container">
          <h4>Id</h4>
          <div class="text space">
            {{project.id}}
          </div>
        </div>
        <div class="container">
          <h4>Owner</h4>
          <div class="text space">
            <app-avatar [userName]="project && project.owner ? project.owner.name : ''" />
            {{ project.owner ? project.owner.name : "" }}
          </div>
        </div>
        <div class="container">
          <h4>Assignee</h4>
          <div class="text">
            <app-assignee-section [assignees]="project ? project.assignments : []"
                                  [data]="project" [dataType]="'project'" />
          </div>
        </div>
        <div class="container">
          <h4>Version</h4>
          <div class="text space">
            <app-versions-section [isEdit]="true" [isProject]="true"
                [version]="getProjectVersion()" (versionNameChange)="changeProjectVersion($event)" />
          </div>
        </div>
        <div class="container">
          <h4>Status</h4>
          <div class="text space">
            <app-status-labeled [isEdit]="true" [(status)]="project.status" (statusChange)="command.editProject(this.project)"/>
          </div>
        </div>
        <div class="container labels">
          <h4 class="label">Labels</h4>
          <div class="text">
            <app-labels-section placeholder="Select label" [(labels)]="project.labels" (labelsChange)="command.editProject(this.project)" />
          </div>
        </div>
        <div class="container">
          <h4>No. of tasks</h4>
          <div class="text space"><a href="/create">
            {{ project && project.tasks ? project.tasks.length : '0' }}
            {{ project && project.tasks && project.tasks.length > 1 ? "tasks" : "task"}}
            <app-icons [ngClass]="'icon'" icon="arrow-right" />
          </a></div>
        </div>
        <div class="container">
          <h4>Created</h4>
          <div class="text space">{{ project.created | dateDifference }}</div>
        </div>
      </div>
      <div class="activity">
        <h3>Last activity</h3>
        <div class="content" *ngFor="let item of activity">
          <div class="img"><app-avatar [id]="item.name" [userName]="item.name" /></div>
          <div class="name">{{ item.name }}</div>
          <div class="desc">{{ item.action }} <a [href]="item.url">{{ item.id }}</a>, {{ item.time | dateDifference }}</div>
        </div>
      </div>
    </aside>
  </div>
</div>
