// 01_Src/01_Client/src/app/compositions/header/header.component.ts
/*****************************************************************************
 * @Author                : 0K00<qdouvillez@gmail.com>                       *
 * @CreatedDate           : 2023-03-20 15:37:13                              *
 * @LastEditors           : 0K00<qdouvillez@gmail.com>                       *
 * @LastEditDate          : 2023-03-20 15:42:46                              *
 *                                                                           *
 ****************************************************************************/

import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  public showModal: boolean = false;
}

<!--
* @Author                : Adrien Lanco<adrienlanco0@gmail.com>
* @CreatedDate           : 2023-03-17 13:48:00
* @LastEditors           : Adrien Lanco<adrienlanco0@gmail.com>
* @LastEditDate          : 2023-03-30 11:01:00
-->

<div id="header">
  <menu class="menu">
    <ng-content></ng-content>
  </menu>
  <app-breadcrumbs class="bread" />
  <div class="setting">
    <app-button id='openSearch' type='trd' size='l'
                (click)='showModal = !showModal'
                icon='search' iconPosition='only'
                [other]="(showModal) ? 'active' : '' " />
    <app-button id='openOption' type='trd' size='l'
                (click)='showOption = !showOption'
                icon='dotshorizontal' iconPosition='only'
                [other]="(showOption) ? 'active' : '' " />
    <ng-container *ngIf="showOption">
      <div @nested class="menuOption">
        <div *ngIf="isAdmin" class="option setting" [routerLink]="['/admin']">Admin</div>
        <div class="option setting" [routerLink]="['/settings']">Settings</div>
        <div class="option disconnect" (click)="disconnect()">Disconnect</div>
      </div>
    </ng-container>
  </div>
  <app-modal [(isOpen)]="showModal">
        <app-search-bar *ngIf="showModal"/>
  </app-modal>
</div>

// 01_Src/01_Client/src/compositions/header/Header.vue
<!--
* @Author                : 0K00<qdouvillez@gmail.com>                         
* @CreatedDate           : 2023-02-24 14:54:57                                
* @LastEditors           : 0K00<qdouvillez@gmail.com>                         
* @LastEditDate          : 2023-02-25 16:01:29                                
*                                                                             
-->

<script lang="ts">
    import { defineComponent } from 'vue';
    import './header.scss';
    import Breadcrumbs from '@/components/breadcrumbs/Breadcrumbs.vue';
    import Modal from "@/layouts/modal/Modal.vue";
    import SearchBar from "@/compositions/searchBar/SearchBar.vue";
    import Button from '@/components/button/Button.vue';
    
    export default defineComponent({
        name: 'Header',

        components: {
          Breadcrumbs,
          Modal,
          SearchBar,
          Button,
        },

        props: {
        },

        computed: {},

        data() {
            return {
              showModal: false,
            }
        },

        methods: {
          closeModal() {
            this.showModal = false
          },
        }
    });
</script>

<template>
  <div id="header">
    <slot class="menu"></slot>
    <Breadcrumbs class="bread" />
    <div class="setting">
      <Button id='openSearch' type='trd' size='l' @click='showModal = true' icon='search' iconPosition='only' v-bind:class = "(showModal)?'active':''" />
      <Button id='openOption' type='trd' size='l' icon='dotshorizontal' iconPosition='only' />
    </div>
    <Modal v-if="showModal" @closeModal='closeModal'>
          <SearchBar />
    </Modal>
  </div>
</template>
